### ISSUE TITLE
Question re: legacy_id_map.csv

### ISSUE THREAD

**Issue by DaSkunk** [guga31bb/nflfastR-data#13]
Is the legacy_id_map csv file supposed to contain all the players in the league? The one I downloaded only has 1667 records. (for example it's missing Saquon Barkley). This file will be immensely helpful to correlate new data against historic data I have indexed with the former player_gsis_id #s. 

Thank you so much for providing this.

**Comment by guga31bb** [comment]
The map is for us to be able to covert everyone who had old IDs (i.e., observed in seasons before 2011) to the new IDs. Since Saquon didn't play before 2011, we don't need to change his ID in any observations. We're abandoning the old IDs because NFL doesn't use them anymore so they're useless going forward (i.e., for rookies in 2020 they won't have old IDs).

I think @ajreinhard has a [full map here](https://github.com/ajreinhard/NFL/tree/master/nflfastR%20ID%20mapping).

**Comment by DaSkunk** [comment]
I understand now, my mistake. I thought only the 2019 pbp data switched to the new ids so I thought the mapping was needed for everything prior to 2019. I see in looking at some of your older JSON, the new IDs are indeed in there.  Thank you for clarifying and responding so quickly.
