### ISSUE TITLE
How to handle challenged and reversed plays?

### ISSUE THREAD

**Issue by james-childress** [guga31bb/nflfastR-data#27]
Hi. Apologies if this has been asked before.

When a play is challenged and reversed, both the reversed play and the following play the replaces it take up one row in the play_by_play data, and the row is annotated with the results of both plays, making it hard to distinguish what is true and what isn't. What's the best way to do this?

For example: game_id = 2020_02_CIN_CLE, play_id = 64

"(14:54) (Shotgun) 9-J.Burrow pass deep left to 18-A.Green ran ob at CLE 26 for 35 yards. CIN-18-A.Green was injured during the play. 
Cleveland challenged the pass completion ruling, and the play was REVERSED.
(Shotgun) 9-J.Burrow pass incomplete deep left to 18-A.Green. CIN-18-A.Green was injured during the play. His return is Probable."

The row is marked with both complete_pass = 1 and incomplete_pass = 1; however, since the completion was reversed, A.J. Green and Joe Burrow are not credited with that completion. Likewise, if it were the opposite way, and the ruling of an incomplete pass were overturned, I anticipate the row would look the same (besides the play description) with both complete_pass = 1 and incomplete_pass = 1. Is this correct? 

When both complete_pass = 1 and incomplete_pass = 1, is there a way to tell which was credited and which was reversed without parsing the play description?

Thanks

**Comment by guga31bb** [comment]
Thank you for raising this. Looked into it and seems like NFL does corrections to play-by-play after the game is over. Since we do the scrape immediately when the game ends, those corrections don't show up unless we delete the original scrape and manually re-scrape.

I have done that for this game and it now has complete_pass == 0 but please let me know if you see any other issues.
