### ISSUE TITLE
Changes in win probability from nfl-scrapR

### ISSUE THREAD

**Issue by robert-moore** [guga31bb/nflfastR-data#42]
There are significant variations in WP in this repo compared to nfl-scrapR, something seems up with the data in this repo (I know that's completely vague). I want to help out and an overview of why these differences are so large would give me a great head start.

Below I've outlined an example where the WP values output by fastR seem volatile and inaccurate (to an eye check). I've put the ESPN win probabilities also for a 3rd party reference

## Example
2019 regular season game between PHI and WAS on 12/15
game_id: 2019_15_PHI_WAS
old_game_id: 2019121508

### Scenario written out in plain text (WP for PHI)
Score: WAS 27 - 24 PHI
Time remaining: 2:26
Possession: PHI on WAS 45
Both teams with 2 timeouts remaining

fastR WP: 32.2%
scrapR WP: 46%
ESPN WP (for ref): 42.3%

**(2:26) PHI pass for 20 yards to WAS 25**
fastR WP: 56.7% (+14%)
scrapR WP: 54.4% (+8%)
ESPN WP: 50.3% (+8%)

**(2:18 1st and 10) PHI pass for -3 yards to WAS 28**
fastR WP: 40.4% (-16%)
scrapR WP: 49.1% (-5%)
ESPN WP: 46.4% (-6%)

**(2:00 2nd and 13) PHI pass for 13 yards to WAS 15**
fastR WP: 66.3% (+26%)
scrapR WP: 58% (+9%)
ESPN WP: 58% (+12%)

**(1:19 1st and 10) PHI rush for 1 yard to WAS 14**
fastR WP: 70.4% (+4%)
scrapR WP: 54% (-4%)
ESPN WP: 54% (-4%)

**Comment by guga31bb** [comment]
Assuming you're using the `wp` column, all 3 of those win probs are bad in different ways. fastR and scrapR don't take point spread into account, while ESPN's model has its own separate issues. There's no reason for fastR and scrapR to have the same results because they are estimated in different ways.

I would recommend using the `vegas_wp` or `vegas_home_wp` fields since those are win probability models that actually take the spread into account and have been tuned well (which is not true of `wp` or `home_wp`).

**Comment by mrcaseb** [comment]
Just for the sake of completeness here the link to our [models article](https://mrcaseb.github.io/open-source-football/posts/2020-09-28-nflfastr-ep-wp-and-cp-models/).

**Comment by guga31bb** [comment]
Closing this but please let us know if you have more questions about the various models (preferably in the nflfastR discord channel)
